### ISSUE TITLE
Проблема с аксессуаром Нацуки

### ISSUE THREAD

**Issue by MrDaseMan** [MrDaseMan/fukuro-storage#152]
![image](https://github.com/MrDaseMan/fukuro-storage/assets/48094227/f30fd4e0-a52b-449a-83c7-ff1009962665)
Аксессуар является литым спрайтом из-за чего перекрывает всё остальное

**Comment by ThomasSamian** [comment]
не баг, а фича)
А если серьёзно, то её добавили чисто, как пасхалку, в самом моде-источнике (Чистовик), откуда этот спрайт, использовался, когда в 6 день отмечали день Нептуна (чего не было в оригинале игры), так что вряд-ли будут это фиксить

**Comment by MrDaseMan** [comment]
> не баг, а фича)

Для Фукуро это, всë же, баг. 

> А если серьёзно, то её добавили чисто, как пасхалку, так что вряд-ли будут это фиксить

С чего такие выводы? На Фукуре полно спрайтов, которые перерисовывались/дорабатывались игроками и мной в том числе, не вижу в этом какой-либо проблемы
