### ISSUE TITLE
Бесконечная плашка

### ISSUE THREAD

**Issue by NazarlusMon** [MrDaseMan/fukuro-storage#164]
>"Теперь инфа о реконекте не будет висеть вечно"

Но будет висеть инфа о том, что не удалось восстановить соединение, даже если оно восстановлено.
![Screenshot_20230919-215634](https://github.com/MrDaseMan/fukuro-storage/assets/80151768/50ef6513-223c-4211-9e85-df4f56361364)

**Comment by MrDaseMan** [comment]
Это технический вопрос, а не связанный с репозиторием ресурсов
